### ISSUE TITLE
No "Template" menu item

### ISSUE THREAD

**Issue by EffeF** [Grafluxe/any-template#2]
I don't have any new menu item after installation.

OS: Manjaro 17 64bit KDE 5.9.4 kernel 4.10.21-1
Brackets: 1.9.0-17312
Any-Template: 2.3.0

**Comment by grafluxe** [comment]
I have not yet tested on any Linux distro. I'll install one and test soon. Thanks for the details.

**Comment by grafluxe** [comment]
@EffeF, I found the issue and will be releasing an update soon. Turns out Brackets on Manjaro does not support extensions written in ES6. My next release (v2.4.0) will support your Linux distro along with adding support for file extensions on newly created files (see the [changelog](https://github.com/Grafluxe/any-template#240)).

Thanks for reporting it.

**Comment by grafluxe** [comment]
v2.4.2 has been released with bug fixes and new features.
